#ifndef PARAMETRIC_PARTICLES_UTILS_API_42_H
#define PARAMETRIC_PARTICLES_UTILS_API_42_H

#ifdef PARAMETRICPARTICLESUTILS_EXPORTS
  #define PARAMETRIC_PARTICLES_API __declspec(dllexport)
#else
  #define PARAMETRIC_PARTICLES_API __declspec(dllimport)
#endif

#endif // PARAMETRIC_PARTICLES_UTILS_API_42_H
